spring:
  application:
    name: bank-rest
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bank
    password: bank
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: "bXktdmVyeS1sb25nLXN1cGVyLXNlY3JldC1rZXktMzItYnl0ZXM="
    expiration-minutes: 60
  card:
    crypto:
      key: "bXktMzItYnl0ZS1zZWNyZXQta2V5LXN0cmluZy0xMjM="

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger



